### PR TITLE
update the container class to oVideo

### PR DESCRIPTION
**Pull request by VladDubrovskis**
/cc @andygnewman @i-like-robots

### CODE REVIEW

**Comment by i-like-robots** [comment]
I guess kill the styles for `.n-content-video__placeholder` but otherwise LGTM

**Comment by VladDubrovskis** [comment]
https://github.com/Financial-Times/n-content-body/pull/32

**Comment by i-like-robots** [comment]
:+1:

**Comment by VladDubrovskis** [comment]
https://github.com/Financial-Times/alphaville-blogs/pull/4

**Pull request closed without merging**
